### PR TITLE
Added aur push output to html view

### PR DESCRIPTION
**Pull request by fmauch**
To debug problems with AUR pushes this adds errors to the package output.

Note that this is untested and I am not familiar with django. So, this might be missing some bits and pieces.

### CODE REVIEW

**Comment by bionade24** [comment]
I changed some stuff to make it a bit better and optional, so it only shows up when `aur_push` is set for the container.

**Comment by bionade24** [comment]
Didn't know that pushing to your branch is possible. Seems like many other persons don't know either and it's a risk for a lot of  hardforks.

**Comment by fmauch** [comment]
> Didn't know that pushing to your branch is possible. Seems like many other persons don't know either and it's a risk for a lot of hardforks.

It's an option when doing a PR. But by default it's on :-)

**Comment by bionade24** [comment]
I'd known that you can edit a PR if enabled, but I didn't know that this lets me add your remote and pushing to it.

Am Donnerstag, 19. November 2020 schrieb Felix Exner:

**Pull request merged**
